[build]
builder = "nixpacks"

[deploy]
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "docker-compose up --build"

[services.variables]
NODE_ENV = "production"

# Entity Relations Service (Port 3002)
[services.entity-relations]
source = "services/entity-relations"
startCommand = "npm start"
[services.entity-relations.variables]
PORT = "3002"

# Entity Search Service (Port 3003)
[services.entity-search]
source = "services/entity-search"
startCommand = "npm start"
[services.entity-search.variables]
PORT = "3003"

# Dataset Matching Service (Port 3004)
[services.dataset-matching]
source = "services/dataset-matching"
startCommand = "npm start"
[services.dataset-matching.variables]
PORT = "3004"

# Data Management Service (Port 3005)
[services.data-management]
source = "services/data-management"
startCommand = "npm start"
[services.data-management.variables]
PORT = "3005"

# Dataset Search Service (Port 3006)
[services.dataset-search]
source = "services/dataset-search"
startCommand = "npm start"
[services.dataset-search.variables]
PORT = "3006"